
clean:
	rm -f *.cex *.o *.elf *.self *.481 *.bin *.map ../lv1/src/*.o ../debug/src/*.o ../lv2/src/*.o

all:
	rm -f *. cex *.o *.elf *.self *.481 *.bin *.480c *.map ../lv1/src/*.o ../debug/src/*.o ../lv2/src/*.o
	make -f Makefile_481C --no-print-directory


